### ISSUE TITLE
Change directory when running Stream Enrich

### ISSUE THREAD

**Issue by robertbakker** [snowplow/snowplow-docker#29]
Hi there,

When I run the example, using docker stack,
The Stream-Enrich service gives me the following exception:

```
docker service logs 50n5v4s44s9b
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | Exception in thread "Thread-5" java.io.FileNotFoundException: ./ip_geo (Permission denied)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at java.io.FileOutputStream.open0(Native Method)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$lessinit$greater$3.apply(ProcessBuilderImpl.scala:33)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$lessinit$greater$3.apply(ProcessBuilderImpl.scala:33)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$lessinit$greater$4.apply(ProcessBuilderImpl.scala:38)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$lessinit$greater$4.apply(ProcessBuilderImpl.scala:38)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder$$anonfun$1.apply$mcV$sp(ProcessBuilderImpl.scala:58)
snowplow-realtime_stream-enrich.1.50n5v4s44s9b@moby    | 	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
```

I am running version:
`Docker version 17.09.0-ce, build afdb6d4` on Mac
and the image is:
`snowplow-docker-registry.bintray.io/snowplow/stream-enrich:0.11.1`

What can I do to solve this ?

Cheers for the great work

**Comment by BenFradet** [comment]
This is most likely due to the `snowplow` user not having the right perms, thanks for the report 👍 

We'll fix this in the upcoming [release 2](https://github.com/snowplow/snowplow-docker/pull/28).
