### ISSUE TITLE
ANLP is not configured correctly with the Scala stream collector for Google Pub/Sub

### ISSUE THREAD

**Issue by ghost** [snowplow/snowplow-docker#56]
**application:** scala-stream-collector-google-pubsub
**version:** 0.13.0

**error:**
``
An error occured: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
``

**Description:**
The deployed application complains about ALPN when trying to deploy the Google Pub/Sub Snowplow collector. 

**System information:**
`` 
JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.4.
``

**Comment by ghost** [comment]
Stacktrace for more info:
```
Exception in thread "main" java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:163)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:546)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:539)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:477)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:325)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:342)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:185)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:147)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:134)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:156)
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:90)
	at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:666)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$$anonfun$com$snowplowanalytics$snowplow$collectors$scalastream$sinks$GooglePubSubSink$$createPublisher$1.apply(GooglePubSubSink.scala:70)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$$anonfun$com$snowplowanalytics$snowplow$collectors$scalastream$sinks$GooglePubSubSink$$createPublisher$1.apply(GooglePubSubSink.scala:70)
	at scala.util.Try$.apply(Try.scala:192)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$.com$snowplowanalytics$snowplow$collectors$scalastream$sinks$GooglePubSubSink$$createPublisher(GooglePubSubSink.scala:66)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$$anonfun$createAndInitialize$2.apply(GooglePubSubSink.scala:45)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$$anonfun$createAndInitialize$2.apply(GooglePubSubSink.scala:42)
	at scalaz.$bslash$div$class.flatMap(Either.scala:134)
	at scalaz.$bslash$div$minus.flatMap(Either.scala:310)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$.createAndInitialize(GooglePubSubSink.scala:42)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector$$anonfun$2.apply(GooglePubSubCollector.scala:38)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector$$anonfun$2.apply(GooglePubSubCollector.scala:31)
	at scalaz.$bslash$div$class.flatMap(Either.scala:134)
	at scalaz.$bslash$div$minus.flatMap(Either.scala:310)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector$.main(GooglePubSubCollector.scala:31)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector.main(GooglePubSubCollector.scala)
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.shaded.io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:34)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
... 29 more
```

**Comment by BenFradet** [comment]
Yup, we're aware of the issue, it will be fixed in the next release where we'll move the gcp images from alpine to debian (c.f. #50 and #52)

**Comment by BenFradet** [comment]
We've now solved this in:

- `snowplow:scala-stream-collector-google-pubsub:0.13.0`
- `snowplow:stream-enrich-google-pubsub:0.17.0`

closing
